services:
  transcribe:
    build: ./transcribe-service
    environment:
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TRANSCRIBE_PORT=8000
    volumes:
      - ./data:/data
    ports:
      - 8000:8000
  web:
    build: ./web
    volumes:
      - ./data:/data
    ports:
      - 8002:80
    environment:
      - APP_ENV=${APP_ENV}
