services:
  translate:
    build: ./translate
    environment:
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TRANSLATE_PORT=8001
    ports:
      - 8001:8001
  transcribe:
    build: ./transcribe-service
    environment:
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TRANSCRIBE_PORT=8000
      - GOOGLE_DRIVE_PROJECT_FOLDER_ID=${GOOGLE_DRIVE_PROJECT_FOLDER_ID}
      - GOOGLE_DRIVE_AUDIO_FOLDER_ID=${GOOGLE_DRIVE_AUDIO_FOLDER_ID}
      - GOOGLE_DRIVE_VIDEO_FOLDER_ID=${GOOGLE_DRIVE_VIDEO_FOLDER_ID}
      - GOOGLE_DRIVE_SRT_FOLDER_ID=${GOOGLE_DRIVE_SRT_FOLDER_ID}
      - GOOGLE_DRIVE_SERVICE_ACCOUNT_CREDENTIALS=${GOOGLE_DRIVE_SERVICE_ACCOUNT_CREDENTIALS}
    ports:
      - 8000:8000
  web:
    build: ./web
    ports:
      - 8002:80
    depends_on:
      - transcribe
