services:
  traefik:
    image: traefik:v2.9
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build: ./transcribe-service
    environment:
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TRANSCRIBE_PORT=8000
    ports:
      - 8000:8000
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${APP_HOST}`) && PathPrefix(`/ws`)"

  frontend:
    build: ./web
    ports:
      - 8002:80
    depends_on:
      - backend
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${APP_HOST}`)"
