name: "Start Bunnyshell Environment"
on:
  schedule:
    - cron: "*/45 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Make sure Bunnyshell is running
        uses: bunnyshell/workflows/.github/workflows/start-env.yaml@v2
        with:
          env-id: ${{ secrets.BUNNYSHELL_DEV_ENV_ID }}
        secrets:
          bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}
